### ISSUE TITLE
What is the expected behavior for RoundedRectangle

### ISSUE THREAD

**Issue by thrisp** [fogleman/gg#10]
using this locally: https://github.com/fogleman/gg/blob/master/examples/mask.go

![out](https://cloud.githubusercontent.com/assets/199137/18959368/eabf2f02-8633-11e6-81b7-69e427f4286c.png)

I get this. Fill & clip do not seem create expected or useful behavior. Stroke seems fine, but otherwise there is unexpected missing area in the center.

**Comment by fogleman** [comment]
I believe I fixed this recently. Make sure you have the latest code:

    go get -u github.com/fogleman/gg

**Comment by thrisp** [comment]
I even scanned over the latest commits, I think I have it installed from a few days previous to those.

**Comment by fogleman** [comment]
No problem. :)
