### ISSUE TITLE
DrawArc: getting rid of the line connecting the center with the beginning.

### ISSUE THREAD

**Issue by lucasepe** [fogleman/gg#106]
Hi! First of all thanks! for your awesome library!

I'm using `gg` to create illustrations about how to do "geometric constructions" .
As you can see in the attached image, drawing arcs shows always the line from the center to the beginning of the arc.
![frame2](https://user-images.githubusercontent.com/585381/88525068-6d416f80-cffa-11ea-8f53-00648b7304fb.png)

I wonder if it would be possible to get rid of that line - drawing only the arc. 

I'm asking for this becouse when the drawing becomes more complex, the result becomes confused.

![frame6](https://user-images.githubusercontent.com/585381/88525729-3fa8f600-cffb-11ea-94f8-d4bbe3ce1992.png)

Maybe it's already possible but I'm missing something?

Thanks!

**Comment by fogleman** [comment]
This should only happen if the context currently has an active path before drawing the arc.

Try `dc.NewSubPath()` before drawing your arc.

**Comment by lucasepe** [comment]
Thank you very much! It works now...and I learned something new!

![sample2](https://user-images.githubusercontent.com/585381/88557572-a8f42d80-d02a-11ea-948e-cd38ceaeb98d.gif)

All the best,
Luca

**Comment by fogleman** [comment]
Nice! I love polygon construction, nice to see this!
