### ISSUE TITLE
Mixing colours

### ISSUE THREAD

**Issue by StarsoftAnalysis** [fogleman/gg#119]
I've noticed that when overlaying colours with alpha < 1.0, the result depends on the order in which the colours are added.  For example, green on red produces a dark green, whereas red on green gives brown.

The attached bit of code shows what I mean: it shows that rgba(1, 0, 0, 0.5) covered by rgba(0, 1, 0, 0.5) gives rgba(0.33, 0.67, 0, 0.75), but rgba(0, 1, 0, 0.5) covered by rgba(1, 0, 0, 0.5) gives rgba(0.67, 0.33, 0, 0.75). 

This is probably done for a good reason, but I'd like to be able to mix colours evenly, so that, for example, rgba(1,0,0,0.5) plus rgba(0,1,0,0.5) always gives rgba(0.5, 0.5, 0, 0.75), irrespective of which is drawn first.

Is there a way of doing that?  I couldn't find the bit in the code that sets the one-third/two thirds ratio.

Here's my code:
```
package main

import (
    "github.com/fogleman/gg"
)   

func main() {
    dc := gg.NewContext(500, 500)
    
    dc.SetRGBA(0.0, 0.0, 0.0, 1.0)
    dc.DrawString("Green over Red:", 100, 90)
    dc.SetRGBA(1.0, 0.0, 0.0, 0.5)
    dc.DrawRectangle(100, 100, 200, 50)
    dc.Fill()
    dc.SetRGBA(0.0, 1.0, 0.0, 0.5)
    dc.DrawRectangle(200, 100, 200, 50)
    dc.Fill()
    
    dc.SetRGBA(0.0, 0.0, 0.0, 1.0)
    dc.DrawString("Red over Green:", 100, 240)
    dc.SetRGBA(0.0, 1.0, 0.0, 0.5)
    dc.DrawRectangle(100, 250, 200, 50)
    dc.Fill()
    dc.SetRGBA(1.0, 0.0, 0.0, 0.5)
    dc.DrawRectangle(200, 250, 200, 50)
    dc.Fill()
    
    dc.SavePNG("ggmixing.png")
}   
```

![ggmixing](https://user-images.githubusercontent.com/842101/101989774-935e6800-3c9a-11eb-9a92-d3a128c3df71.png)

**Comment by StarsoftAnalysis** [comment]
Further investigation reveals that other packages (e.g. [draw2d](https://pkg.go.dev/github.com/llgcode/draw2d)) do the same thing.

In fact the formula given in [Wikipedia](https://en.wikipedia.org/wiki/Alpha_compositing#Alpha_blending) does too, so I obviously need a different approach to get the effect I want.

**Comment by Plazmaz** [comment]
@StarsoftAnalysis what did you end up doing here? I'm experiencing this, where I have two images with alpha values < 1, and want to overlay them, and the two red images output a green overlap...

**Comment by StarsoftAnalysis** [comment]
Hi @Plazmaz.  It's a while ago, and I haven't used gg recently.  I think I tried to invent my own ways of working with alpha values, got very confused, and gave up.  Sorry -- that's not very helpful.

**Comment by Plazmaz** [comment]
@StarsoftAnalysis all good! For future people, using NRGBA colors fixed it
