### ISSUE TITLE
can gg writes in a circle pattern?

### ISSUE THREAD

**Issue by JasonkayZK** [fogleman/gg#120]
I'm drawing some pattern like this:
![图片1](https://user-images.githubusercontent.com/40811521/103255871-fdc71600-49c5-11eb-86c6-b90d46aecc9d.png)

so, i wonderred if gg can write text like this?

**Comment by fogleman** [comment]
Unfortunately there isn't a way to do this currently.

**Comment by JasonkayZK** [comment]
thanks, man!
