### ISSUE TITLE
draw two text in different rotation with accurate x, y ?

### ISSUE THREAD

**Issue by JasonkayZK** [fogleman/gg#121]
I try to draw two text in different rotation degrees, but i found it wrong that the text is not in the exact x, y which has been given:
```go
func main() {
	F := 40.0
	dc := gg.NewContext(500, 500)
	dc.Clear()

	if err := dc.LoadFontFace("Deng.ttf", F); err != nil {
		panic(err)
	}

	dc.SetRGB(1, 0, 0)
	dc.SetLineWidth(4)

	dc.Rotate(gg.Radians(30))
	dc.DrawStringAnchored("Hello 1", 200, 200, 0.5, 0.5)
	dc.Rotate(gg.Radians(30))
	dc.DrawStringAnchored("Hello 2", 300, 300, 0.5, 0.5)

	dc.Fill()

	_ = dc.SavePNG("out.png")
}
```

The result img below:

![out](https://user-images.githubusercontent.com/40811521/103400145-00b93680-4b7f-11eb-9b73-6e4f6465f73e.png)

Even the "Hello 2" is not in the image?!

**Comment by fogleman** [comment]
Rotation occurs about the origin. You can try the RotateAbout function to rotate about a different location.

**Comment by JasonkayZK** [comment]
This does solve the problem. But new problem occurred when I was trying to create two different string:

```go
	F := 40.0
	dc := gg.NewContext(500, 500)
	dc.Clear()

	str1 := "Hello 1"

	if err := dc.LoadFontFace("Deng.ttf", F); err != nil {
		panic(err)
	}

	dc.SetRGB(1, 0, 0)
	dc.SetLineWidth(4)

	w, h := dc.MeasureString(str1)
	dc.RotateAbout(gg.Radians(30), 200-w/2, 200 - h/2)
	dc.DrawString(str1, 200, 200)
	dc.RotateAbout(gg.Radians(30), 200-w/2, 200 - h/2)
	dc.DrawString("Hello 2", 200, 200)

	dc.Fill()
	_ = dc.SavePNG("out.png")
```

The result is below:

![out](https://user-images.githubusercontent.com/40811521/103769421-2d79bc00-505f-11eb-8945-cf31e5ab0b9a.png)

It seems that the second string is influenced by the first drawing. So i was wondering if there has any API that could draw the second string without being influenced by the frist `RotateAbout` ?

**Comment by fogleman** [comment]
Use dc.Identity() to reset the transformation function. Alternatively, nest the transformations within dc.Push(), dc.Pop()

**Comment by JasonkayZK** [comment]
thanks, problem solved!
