### ISSUE TITLE
Question: How to draw a point ?

### ISSUE THREAD

**Issue by fu607666** [fogleman/gg#13]
I used DrawCircle to draw a point, but the point was scaled.

```go
func main() {
	dc := gg.NewContext(300, 300)

	dc.SetRGB(1, 1, 1)
	dc.Clear()
	dc.SetRGB(0, 0, 0)

	dc.Scale(5, .1)

	n := 100.0
	r := 1.0
	for i := 1.0; i < n; i++ {
		dc.DrawCircle(i, i, r)             // DrawPoint
		dc.DrawCircle(i, i*i, r)           // DrawPoint
		dc.DrawCircle(i, i*math.Log(i), r) // DrawPoint
	}
	dc.Fill()

	dc.SavePNG("out.png")
}
```

![out](https://cloud.githubusercontent.com/assets/20315889/20665711/97e3c008-b59b-11e6-8182-bf449dbb65e4.png)

**Comment by fogleman** [comment]
Do you want to set the color of a single pixel or do you want a circle that is translated/rotated according to the current transform but not scaled?

**Comment by fogleman** [comment]
Added a `DrawPoint` method that transforms the location of the point being drawn but not its size or shape:

![out](https://cloud.githubusercontent.com/assets/520208/21198040/bc605e9c-c20b-11e6-9329-62c93213229b.png)
