### ISSUE TITLE
Context.SetFontFace doesn't update fontHeight (fix enclosed)

### ISSUE THREAD

**Issue by mattsiegel** [fogleman/gg#15]
MeasureString may return an incorrect height without this one-line addition :)

func (dc *Context) SetFontFace(fontFace font.Face) {
	dc.fontFace = fontFace
	dc.fontHeight = float64(fontFace.Metrics().Height) / 64
}

**Comment by fogleman** [comment]
Thanks!

**Comment by yoki123** [comment]
The fontHeight in LoadFontFace is `points * 72 / 96`, I got different fontHeight while using SetFontFace.
