### ISSUE TITLE
FSavePNG(io.Writer, image.Image) variant

### ISSUE THREAD

**Issue by odeke-em** [fogleman/gg#2]
I wanted to ask if adding an FSavePNG function would be something that you'd consider. The reason for this is, I can connect your package to a web server or for usage where I wouldn't like to write to disk and easily connect it to other usages since it will take an io.Writer.
Also this means that we can also reuse FSavePNG in SavePNG in such a fashion.
```go
func SavePNG(path string, img image.Image) error {
    f, err := os.Create(path)
    if err != nil {
      return err
    }
   defer f.Close()
   return FSavePNG(f, img)
}

func FSavePNG(w io.Writer, img image.Image) error {
    return png.Encode(w, img)
}
```

If this is something you'd consider, please let me know and I can create a PR for it.
Thank you.

**Comment by fogleman** [comment]
You could do this with the current API:

    png.Encode(w, dc.Image())

But I still like the idea. What if we call it `EncodePNG` instead of `FSavePNG`? Also add it to the `Context`, so you can do:

    dc.EncodePNG(w)

**Comment by odeke-em** [comment]
Sounds like a plan. Cool, let me jump on it.
