### ISSUE TITLE
miss func to set fontHeight

### ISSUE THREAD

**Issue by deathkel** [fogleman/gg#21]
I want to change font point without reload FontFace when I draw string .How can I do that

**Comment by fogleman** [comment]
There's no way to do that with the current API. But you can copy the code linked below to manage it yourself, and just call `dc.SetFontFace()` with the `font.Face` that you create.

https://github.com/fogleman/gg/blob/master/util.go#L103-L117

I'll think about making a change to support this though.

**Comment by deathkel** [comment]
thx

**Comment by yanyuxuanz** [comment]
I have the Same Question with you.Could the author expose an api like dc.Setfontheight(),The Func of SetFontFace and LoadFontFace have different FontHeight as result.What should I do when I just want  to change the fontHeight?
