### ISSUE TITLE
gg doesn't render rtl and bidi text correctly

### ISSUE THREAD

**Issue by dariubs** [fogleman/gg#32]
There is some problem to render rtl languages text (like arabic, persian, kurdish, hebrew and ...) in gg.
The glypes doesnt render currectly.

Example:
```golang
package main

import (
    "github.com/fogleman/gg"
    "log"
)

func main() {
    const S = 1024
    im, err := gg.LoadImage("img.jpg")
    if err != nil {
        log.Fatal(err)
    }

    dc := gg.NewContext(S, S)
    dc.SetRGB(1, 1, 1)
    dc.Clear()
    dc.SetRGB(0, 0, 0)
    if err := dc.LoadFontFace("/home/dariush/Newsify/css/iransans/ttf/font.ttf", 96); err != nil {
        panic(err)
    }
    dc.DrawStringAnchored("سلام", S/2, S/2, 0.5, 0.5)

    dc.DrawRoundedRectangle(0, 0, 512, 512, 0)
    dc.DrawImage(im, 0, 0)
    dc.DrawStringAnchored("سلام", S/2, S/2, 0.5, 0.5)
    dc.Clip()
    dc.SavePNG("out.png")
}

```

output : 
![out](https://user-images.githubusercontent.com/3078072/32379502-ef80b9b4-c0c2-11e7-902f-caa66a3c398b.png)

**Comment by arastu** [comment]
What has happened to this issue? As well, I faced the same problem.
cc: @fogleman

**Comment by arastu** [comment]
It does not seem to be a gg problem, ss mentioned in https://github.com/golang/go/issues/27281, the text shaping API is not yet implemented in Golang.
