### ISSUE TITLE
Question - is it possible to use gradients in text?

### ISSUE THREAD

**Issue by Xopherus** [fogleman/gg#34]
Say I wanted to simulate really really bad word art - like old school Microsoft Word memes. I've tried to do something like this:

```
grad := gg.NewLinearGradient(0, 72, 0, 72)
grad.AddColorStop(0, color.RGBA{63, 191, 63, 255})
grad.AddColorStop(1, color.RGBA{248, 43, 16, 255})

c.SetStrokeStyle(grad)
c.LoadFontFace("Impact.ttf", 72)
c.DrawStringAnchored(fmt.Sprintf("Friendship ended with %s", oldFriend), float64(500), float64(50), 0.5, 0.5)
c.Stroke()
```

**Comment by fogleman** [comment]
It wasn't possible, but I just now made it possible by adding two new functions.

https://github.com/fogleman/gg/commit/1b3894b02865976c26441d149c1b8e8f17358b54

Also added examples/gradient-text.go to demonstrate.

![out](https://user-images.githubusercontent.com/520208/36083548-8b069fae-0f81-11e8-9c0b-1b6895fe834c.png)

**Comment by Xopherus** [comment]
@fogleman this is fantastic. Thank you!

**Comment by nathfreder** [comment]
@fogleman Is it possible to alternate colors? I want an effect similar to what Google has.
<img width="277" alt="Screen Shot 2019-04-15 at 8 32 35 AM" src="https://user-images.githubusercontent.com/40307305/56129657-19239080-5f59-11e9-9227-a65c691bf904.png">
