### ISSUE TITLE
Line width fine-control

### ISSUE THREAD

**Issue by jdevelop** [fogleman/gg#35]
I am trying to create the bimaps, and looks like I can't have vertical or horizontal line of width of exactly `1 px`. Is there any way of making the width "strict"?

**Comment by fogleman** [comment]
This is a common problem when using antialiasing renderers. The trick is to draw the line in the "middle" of a pixel, e.g. x = 0.5

I added an example to demonstrate:

https://github.com/fogleman/gg/blob/master/examples/crisp.go

**Comment by fogleman** [comment]
I wouldn't suggest vector fonts on such a display but rather some bitmap-based font.

**Comment by jdevelop** [comment]
Can `gg.Context` work with bitmap fonts?

**Comment by fogleman** [comment]
The default font is `basicfont.Face7x13`. Try rendering text without setting a new font.

**Comment by fogleman** [comment]
Should look something like this (zoomed in)

![screen shot 2018-02-23 at 11 38 12 am](https://user-images.githubusercontent.com/520208/36605197-0c9c658e-188e-11e8-9749-f96541567c70.png)

**Comment by jdevelop** [comment]
Perfect, that worked! Can I use other bitmap fonts?

**Comment by fogleman** [comment]
I think that's the only such font that's built in.

https://godoc.org/golang.org/x/image/font/basicfont

**Comment by jdevelop** [comment]
Oh, I see - looks like there're some ways to load the custom bitmaps. Thanks a lot :) I think this one can be closed.
