### ISSUE TITLE
Can not open OpenSans 

### ISSUE THREAD

**Issue by vit1251** [fogleman/gg#36]
I download Open-Sans font from Google and start draw text but receive error:

`panic: freetype: invalid TrueType format: bad kern table length`

Could you explain me what happend and whats wrong I doing?

**Comment by fogleman** [comment]
This error comes from: https://github.com/golang/freetype

Try filing this bug there.

**Comment by vit1251** [comment]
Google already know about problem in https://github.com/golang/freetype/issues/8
