### ISSUE TITLE
Question: what contextcan it render to ?

### ISSUE THREAD

**Issue by joeblew99** [fogleman/gg#4]
Desktop using opengl ?
Windows, Linux, OSX ?
Maybe mobile ?

Then I am wondering about update speeds etc ?
If you out a game loop under it for example. Or is it really not designed for this ?

**Comment by fogleman** [comment]
You could use go-gl to blit the image in a window. But it's not really designed for realtime rendering.

**Comment by WhisperingChaos** [comment]
@joeblew99 

Although this request is a few years old, just wanted to mention this golang [github gui project](https://github.com/faiface/gui) that uses [gg](https://fgithub.com/fogleman/gg) to render gg's API onto a minimalist _concurrent_ GUI.  I'm using Ubuntu as my development platform and so far I've been very pleased with the combined results of the two projects.   The gui project uses [GLFW](https://www.glfw.org/) as an interface to opengl.   According to GLFW's website, it should work on the desktop platforms mentioned above.

**Comment by Leadrive** [comment]
@WhisperingChaos the newest gui version use glfw now.
I viewed all the history, did not find the gg version.
Do you have it? I need a gui with gg.
Thank you.
