### ISSUE TITLE
Could you please give me a example to scale image?

### ISSUE THREAD

**Issue by h3l** [fogleman/gg#41]
I'm not a old hand handle with image.
i just want to make a 1000 * 1000 pixel image to 100 * 100 pixel image.
with I Scale method didn't work and I can't find a example to do such thing.
Could you please just give me a snippet about it?

**Comment by fogleman** [comment]
`gg` doesn't do image resizing, but you can use this library for that:

https://github.com/nfnt/resize

**Comment by h3l** [comment]
Thank you very much!
