### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by wayneashleyberry** [fogleman/gg#43]
The latest release, `1.0.0` doesn't handle image rotation correctly. This has been fixed in master, but pulling the latest tag will give you broken or old behaviour. I just spent quite a long time debugging inconsistent behaviour between my project and running the examples, only to find that `dep` will default to the latest tag, so I had to switch to the master branch manually.

**Comment by fogleman** [comment]
Good idea. Just added v1.1.0 release. Thanks.
