### ISSUE TITLE
LoadFontFace support for gofont

### ISSUE THREAD

**Issue by maugsburger** [fogleman/gg#45]
The packets in https://godoc.org/golang.org/x/image/font/gofont supply font data for easy inclusion, but there is no method to load the font from a slice.

Therefore, I would like to ses a "ParseFontFace" for this purpose.

**Comment by fogleman** [comment]
Sounds like a good feature!

**Comment by fogleman** [comment]
@maugsburger No need for an API change, see the new gofont.go example from 0e0ff3a

**Comment by maugsburger** [comment]
@fogleman lovely, thanks ❤️
