### ISSUE TITLE
Opition to turn anti-aliasing off ?

### ISSUE THREAD

**Issue by di3663** [fogleman/gg#47]
Anti-aliasing makes pictures very larger,  in some contexts, smaller is better. For example, a captcha gg generated is 8x larger than gd.

go-gg

![captcha-go-gg](https://user-images.githubusercontent.com/36250009/45131215-8189e280-b1be-11e8-8d61-c4d8fd1c337b.png)

php-gd

![captcha-php-gd](https://user-images.githubusercontent.com/36250009/45131216-8189e280-b1be-11e8-81d2-51ad4a0acb2a.png)

**Comment by fogleman** [comment]
@di3663 Unfortunately there is currently no such option in gg.
