### ISSUE TITLE
Text drawn with DrawStringWrapped appears in discrete characters for Arabic 

### ISSUE THREAD

**Issue by emad-elsaid** [fogleman/gg#57]
When writing a text in arabic the characters are connected as follows : 
```
عبد الفتاح السيسي
```

When I tried to use `DrawStringWrapped` it drawn the text in a descrete way, every character is not connected as follows:
![image](https://user-images.githubusercontent.com/54403/50734122-0d764000-119a-11e9-9d7d-1bedcfd34c60.png)

The code snippet that generated the text in that image is as follows:
```go
func drawName(dc *gg.Context, name string) {
	const height = 250
	dc.SetRGB(0, 0, 0)
	dc.DrawRectangle(0, HEIGHT-height, WIDTH, height)
	dc.Fill()

	if err := dc.LoadFontFace("font.ttf", 70); err != nil {
		return
	}
	dc.SetRGB(1, 1, 1)
	dc.DrawStringWrapped(name, 100, HEIGHT-height+70, 0, 0, WIDTH-200, 1.5, gg.AlignLeft)
	dc.Fill()
}
```

**Comment by fogleman** [comment]
@nigeltao Is this something I'm doing wrong or does `freetype` have the same problem?

**Comment by nigeltao** [comment]
Freetype-go has the same problem: it does not do text shaping. We'd need the Go equivalent of the Harfbuzz library, but that's a *lot* of work, and I don't have any spare time. Sorry.

**Comment by AbdullahDiaa** [comment]
I've created a library to help fixing the text shaping issue for arabic:
https://github.com/AbdullahDiaa/ar-golang

I hope it's helpful.
