### ISSUE TITLE
TestPushPop fails with future Go 1.12

### ISSUE THREAD

**Issue by ianlancetaylor** [fogleman/gg#58]
When running `go test` with the future Go 1.12 release, `TestPushPop` fails:

```
> go test
--- FAIL: TestPushPop (0.00s)
    context_test.go:26: expected hash: e0d6724eb72033577811a55f7a642f6a != actual hash: 31e908ee1c2ea180da98fd5681a89d05
FAIL
exit status 1
FAIL	github.com/fogleman/gg	0.042s
```

This appears to be due to https://golang.org/cl/153059, which changes the exact bit results returned by some trigonometric math functions.  `TestPushPop` appears to be a change-detector test (https://testing.googleblog.com/2015/01/testing-on-toilet-change-detector-tests.html) in that it basically tests that some floating point operations return bit-for-bit identical results.

**Comment by fogleman** [comment]
Updated test for 1.12.
