### ISSUE TITLE
Subtract alpha from underlying shape

### ISSUE THREAD

**Issue by jpmeijers** [fogleman/gg#59]
I am creating an image and filling it with black by drawing a rectangle to the context. I then want to draw circles in alpha on top of the image so that there are hole punches in it. Drawing circles to the context in alpha will just make invisible circles on to of the black rectangle, leaving me with a full black image. How do I make the drawing of the circles subtract colour from the rectangle?

Otherwise, perhaps there is a different method to obtain an image like the following one where the white should be transparent.
![image](https://user-images.githubusercontent.com/948278/51085423-7f71fa80-1741-11e9-95db-210883a9d059.png)

**Comment by fogleman** [comment]
Just added a new `InvertMask` function that makes this easy. Also added an example.

https://github.com/fogleman/gg/commit/cdabe43353c1c54609bd241c92baecadde64b810

Proper alpha compositing (Porter Duff) would probably be best, but this will work for now.

**Comment by jpmeijers** [comment]
Wow, thanks a lot!

The example works perfectly for my use.

**Comment by jpmeijers** [comment]
After some further development on my side I thought it could be nice if I soften the edges of the circles I cut out of the black background. My end goal is to draw "fog of war". Using the `RadialGradient` I can get this effect on a single circle. But when two circles overlap the gradients add together.

Do you have any suggestion how one can get a gradient edge around an area?

My example code just for reference:
```
package main

import (
	"github.com/fogleman/gg"
	"image/color"
	"log"
)

func main() {
	dc := gg.NewContext(256, 256)

	grad := gg.NewRadialGradient(100, 100, 20, 100, 100, 40)
	grad.AddColorStop(0, color.RGBA{0, 0, 0, 0})
	grad.AddColorStop(1, color.RGBA{0, 0, 0, 255})

	dc.DrawCircle(100, 100, 41)
	dc.SetFillStyle(grad)
	dc.Fill()


	grad = gg.NewRadialGradient(100, 150, 20, 100, 150, 40)
	grad.AddColorStop(0, color.RGBA{0, 0, 0, 0})
	grad.AddColorStop(1, color.RGBA{0, 0, 0, 255})

	dc.DrawCircle(100, 150, 41)
	dc.SetFillStyle(grad)
	dc.Fill()
	

	dc.DrawCircle(100, 100, 40)
	dc.DrawCircle(100, 150, 40)
	dc.Clip()
	dc.InvertMask()
	dc.DrawRectangle(0, 0, 256, 256)
	dc.SetRGB(0, 0, 0)
	dc.Fill()


	err := dc.SavePNG("test.png")
	if err != nil {
		log.Print(err.Error())
	}
}
```
