### ISSUE TITLE
Ignore stroke on the edge of image

### ISSUE THREAD

**Issue by ivanjaros** [fogleman/gg#62]
Hi,
I am drawing a map tiles and I am ending up with edges of the image filled with stroke since it follows the path of a polygon to fill and stroke. When polygon overlaps the tile the edge of the image should not be stroked since it visually divides the polygon. So far I have tried to see if any edge of the image is filled with the same color that does not match the same line -1px inwards into the image but even with this fix I am still getting the edges which I think is the result of aliasing which accoridng to another issue cannot be turned on. So I wonder what would be a good way to disable stroke once on image's edge?

![invert](https://user-images.githubusercontent.com/3159095/52334462-0728ed00-2a00-11e9-9d9a-3dd20e9aa046.png)

See the grid - there is no grid, that's just the stroke following the path of the polygon. On the bottom left you can see it "fixed", the thin blue line, it is still there even with my fix. 

PS: This is fix with transparent stroke on the edges - there is still a visible line.
![transp](https://user-images.githubusercontent.com/3159095/52335329-6e47a100-2a02-11e9-8a96-bf2e663ed790.png)

Solved by using draw2d library and setting fill rule to draw2d.FillRuleWinding with transparent border fix.

**Comment by fogleman** [comment]
Winding fill rule is available in gg also.

You can probably get rid of the thin line by drawing on the "middle" of pixels, e.g. offset by 0.5, as demonstrated in the "crisp" example.

https://github.com/fogleman/gg/blob/master/examples/crisp.go

**Comment by ivanjaros** [comment]
Just in case someone encounters the same issue - this is my working solution:
```
       
       img.SetFillRuleEvenOdd()


        // detect lines going along the edge of a tile
	var wasEdgeX bool
	var wasEdgeY bool
	limit := float64(tiles.TileSize - 1)
	for k := range pixels {
		pt := [2]float64{float64(pixels[k].X - base.X), float64(pixels[k].Y - base.Y)}

		edgeX := pt[0] <= 1 || pt[0] >= limit
		edgeY := pt[1] <= 1 || pt[1] >= limit

		move := k == 0

		if edgeX && wasEdgeX {
			move = true
		}

		if edgeY && wasEdgeY {
			move = true
		}

		wasEdgeX = edgeX
		wasEdgeY = edgeY

		if move {
			img.MoveTo(pt[0], pt[1])
		} else {
			img.LineTo(pt[0], pt[1])
		}
	}

	if closed {
		img.LineTo(float64(pixels[0].X - base.X), float64(pixels[0].Y - base.Y))
	}
```
