### ISSUE TITLE
Continue line stroke to the end of the edge - line cap

### ISSUE THREAD

**Issue by thumbsized** [fogleman/gg#63]
I am rendering a map and the paths(roads) are just lines so in order to make them thicker I had to use two strokes to simulate fill. This works without any issues and complex math for tessellation(at least I think that is what is used for this problem). The issue I am encountering is that the stroke will not continue to the edge of the image. Specifically, one side will turn inwards right before the edge of the image. When two opposing lines are rendered on two neighbouring images it creates visually broken path. 

I am using rounded line cap, when I use butt the stroke will simply stop before reaching the edge. So obviously what is happening is that the original center of the line is reaching the edge of the image, yet the stroke continues a bit(outward side) until it reaches the 90 degree angle and stops. This if course happens only with some angles of the path. When this happens the rounding will take place(gg.LineCapRound) or nothgin. So the issue is that I need to prolong the stroke somehow.

Any idea how to fix this? One thing that comes to mind is somehow tricking the renderer to go past the edge of the image but am not sure how exactly.

![zoom](https://user-images.githubusercontent.com/3159095/52540280-291bca00-2d88-11e9-8308-d2f7ae42a12c.png)

---
**I have fixed it by enlarging the image and drawing over it, then cropping it back to original size.** But I wonder if aforementioned issue sohuldn't have a GG solution as well? Specifically, line cap setting that would make the stroke follow the edge where the end of the line actually ends. The outward stroke line already does it for rounded cap so there is a mechanism in place that could achieve this.

**Comment by fogleman** [comment]
You'll have to extend the lines before drawing them. Map tiles are often padded for this very reason.
