### ISSUE TITLE
context.SetDashOffset not included in the v1.2.0 zip

### ISSUE THREAD

**Issue by seanschen** [fogleman/gg#66]
I tried pulling in fogleman/gg as a dependency of gonum/plot but I'm running into a compile error because the SetDashOffset method is not included in the v1.2.0 release zip or tar. It looks like the commit is included in the history but the method is missing in the gofile. Can you fix this? @fogleman

**Comment by fogleman** [comment]
I just cut a new release:

https://github.com/fogleman/gg/releases/tag/v1.3.0

**Comment by seanschen** [comment]
Awesome, it works now. Thank you!
