### ISSUE TITLE
draw polygon with different border and fill colors 

### ISSUE THREAD

**Issue by CamiloGarciaLaRotta** [fogleman/gg#68]
Hi!

Awesome library, it's a joy to use!

I just want to make sure there isn't another way of creating a polygon (e.g. a circle)
which has its border of a given color and its filling of a different color.

My current approach is to draw 2 circles, the smaller one after the bigger one.

Cheers

**Comment by fogleman** [comment]
```go
// add your path
dc.DrawCircle(...)
// fill it in with some color, preserve the current path
dc.SetRGB(...)
dc.FillPreserve()
// stroke it with a certain color and stroke width
dc.SetRGB(...)
dc.SetLineWidth(10)
dc.Stroke()
```

**Comment by CamiloGarciaLaRotta** [comment]
works like a charm, thanks!
