### ISSUE TITLE
SetPixel is here, but what about GetPixel ?

### ISSUE THREAD

**Issue by einar-indrida** [fogleman/gg#69]
Hi... I'm looking at your excellent gg package.  I notice a thing (but that is maybe just me)...

I see a SetPixel() ... but I don't see a GetPixel() ?

When you are drawing a lot (especially overlapping), it would be nice to be able to pull back out, the color of each pixel, and see if that is the color you expected ......

**Comment by einar-indrida** [comment]
Would the following, placed in context.go, work?

// GetPixel gets the color of the specified pixel using the current color.                                                                                                                     
func (dc *Context) GetPixel(x, y int) color.Color {                                                                                                                                            
    return dc.im.At(x, y)                                                                                                                                                                      
}

**Comment by fogleman** [comment]
Something like that should work. Note that you can already achieve this with

```dc.Image().At(x, y)```

**Comment by einar-indrida** [comment]
Oobs.  I'm still picking up Go, and found the GetPixel() missing.  But of course.

Thanks,

**Comment by dondish** [comment]
Close the issue?

**Comment by einar-indrida** [comment]
Good idea :)  Sorry for me being late to close it.
