### ISSUE TITLE
About image quality

### ISSUE THREAD

**Issue by Seaony** [fogleman/gg#78]
Hi guys. thank you for your work.

In the past few days, I have tried to use this package to make poster images. Everything is fine, but I have some doubts about the image quality.
Please see this:

<img width="1155" alt="WX20190616-022915@2x" src="https://user-images.githubusercontent.com/29486364/59555045-3a4b4080-8fdf-11e9-9873-1863b3c6a51e.png">

On the left is the generated image, and the design on the right
The resulting image quality is quite different from the design draft. 
I also tried to use PHP GD and PHP Imagick, and the same happened.
I want to know why, for what reason, thank you.

**Comment by Seaony** [comment]
and. Fonts introduced by LoadFontFace cannot control word weight

**Comment by Seaony** [comment]
Life continues, I solved the problem with a magnification scheme

**Comment by evanfrawley** [comment]
> magnification scheme

@Seaony if you remember 3 years later, what is a magnification scheme?

**Comment by shiguanghuxian** [comment]
@Seaony 请问，这个字体加粗具体怎么实现的呢
