### ISSUE TITLE
LoadFontFace returns only error, method for saving/reusing a font?

### ISSUE THREAD

**Issue by vadimyer** [fogleman/gg#8]
Using LoadFontFace for constant switching between fonts is a bit tedious (considering it always loads the file drom disk).
There's a method SetFontFace, it takes a font.Face type but how could we fill this type?
Thanks.

**Comment by fogleman** [comment]
You can see how `gg` loads font.Face here:

https://github.com/fogleman/gg/blob/master/util.go#L102

Perhaps this utility function should be exported?

**Comment by vadimyer** [comment]
Yeah that's what I mean.
