### ISSUE TITLE
How do you resize an image to fit a specific width/height

### ISSUE THREAD

**Issue by pollen5** [fogleman/gg#86]
I'm rewriting a project from JavaScript (Node.js) to Golang, for the image parts i decided to use this library but how do you resize an image to fit a specific width/height, i'm working with a situation where images are dynamic and can have any sizes, in JavaScript the library i used offered an `addImage(img, w, h, x, y);` where i could tell the size i need for img to be, so it always fitted the box i wanted to add an image on top of.

**Comment by fogleman** [comment]
`gg` itself doesn't do resizing, you can try one of these:

https://github.com/disintegration/imaging
https://github.com/nfnt/resize

**Comment by pollen5** [comment]
Perfect, Exactly what i needed! Thank You!
