### ISSUE TITLE
DrawString isn't working

### ISSUE THREAD

**Issue by pollen5** [fogleman/gg#87]
DrawString does not draw anything for me, do i have to load a font? Does it have a default font? I tried loading a font but it didn't help. All i'm doing is a basic `ctx.DrawString("some string", 16, 16)`

**Comment by fogleman** [comment]
Are you setting the color first? Did you try the text examples from the examples directory?

**Comment by pollen5** [comment]
@fogleman the text example worked (commented the font part), not sure what was i doing different, i think it was the color, also what font is gg using by default? and how can you change the text size to be bigger?

**Comment by pollen5** [comment]
@fogleman are you alive? I still need help on how to change font size, I'm going to work on my project again soon and really need this.

**Comment by pollen5** [comment]
Nevermind
