### ISSUE TITLE
Question / Is is possible to draw a rounded image from a rectangle one ?

### ISSUE THREAD

**Issue by BenjaminCh** [fogleman/gg#9]
Hello, 

Just wanted to know if there is a way I can draw a rounded rectangle image (from existing image rectangle image)? 

I tried couple times but without any results, I am probably missing something. 

What I tried : 
   - Draw a rounded rectangle 
   - Apply Fill()
   - Draw the image on top  

Example : 
I have a 300x150 raw image. I want to draw it in a context so it will become a rounded image (with a given radius) of the same size 300x150.

Is there any way of doing so ?

Thanks a lot.
Ben

**Comment by fogleman** [comment]
You want to use `Clip()`. I committed a new example to demonstrate.

https://github.com/fogleman/gg/commit/b28a9453d48f7f1cf2056cc87771610cac326b78

**Comment by BenjaminCh** [comment]
Whooo ! Super, thanks a lot :)
