### ISSUE TITLE
Draw straight vertical\horizontal line 1px width

### ISSUE THREAD

**Issue by fordarian** [fogleman/gg#90]
Hello. I need to draw some grids with 1 pixel wide lines. But LineTo\DrawLine functions produce 2px wide lines, even with SetLineWidth(1). The coordinates have no fractured parts. The only way i managed to plot them correctly is using SetPixel function. Is it the only and correct way?

**Comment by fogleman** [comment]
You need to offset them by 0.5 to get crisp lines. This is common for antialiasing rasterizers: http://usefulangle.com/post/17/html5-canvas-drawing-1px-crisp-straight-lines

**Comment by fordarian** [comment]
Works perfect, thank you!
